### ISSUE TITLE
Data model

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#1]
Initial pass at the combined data model. To be iterated on.

<img width="1130" alt="screen shot 2018-05-29 at 16 21 04" src="https://user-images.githubusercontent.com/12719553/40668784-516be74c-635d-11e8-93da-d5d3645a47d3.png">

**Comment by astroash** [comment]
Updated:

<img width="934" alt="screen shot 2018-05-29 at 5 57 54 pm" src="https://user-images.githubusercontent.com/14337958/40673548-fa0c3b48-6369-11e8-84c6-b0c387e140b1.png">

**Comment by eliascodes** [comment]
Can probably remove the foreign key to `organisation` from `visit`, since it's linked via `visit_activity`.

**Comment by astroash** [comment]
# v1.3
<img width="1242" alt="screen shot 2018-05-30 at 5 41 03 pm" src="https://user-images.githubusercontent.com/14337958/40734567-b59d7fae-6430-11e8-8be9-68c830a1c463.png">

**Comment by eliascodes** [comment]
Also `name` seems to be a (semi-)reserved word, so we should be more specific with column names.

**Comment by eliascodes** [comment]
Also remove `deleted` from `visit_activity`

**Comment by eliascodes** [comment]
#v1.4

Fixed the stuff I mentioned, added the suggested permissions/roles structure from #2 and fixed `visit` table not linking to `user` table.

![screen shot 2018-05-31 at 14 30 53](https://user-images.githubusercontent.com/12719553/40785067-65d9c4aa-64df-11e8-98c2-0ec0d9a91dbb.png)

**Comment by eliascodes** [comment]
I think so 🤔

**Comment by astroash** [comment]
🔶 - all apps
🍏 - visitor app
🚙 - volunteer app
💜 - twine dashboard

**Comment by eliascodes** [comment]
More:
* Subscriptions need an expiry
* Subscriptions needs to keep track of concept of "owner" and "beneficiary" of subscription since sector orgs buy and manage the subs on behalf of beneficiaries.
* Table to record trainings/workshops
* Optionally record post-code for visitors/volunteers
* Record meetings w/ local community members
* Funder table
* Funding programme table
* Record all CB logins

**Comment by eliascodes** [comment]
Update:

![screen shot 2018-06-01 at 14 50 07](https://user-images.githubusercontent.com/12719553/40844208-3bf3139a-65ab-11e8-9904-00115b6445a3.png)

The tables in grey remain an area of uncertainty in terms of whether they're modeled correctly. In particular, the above model was made using the following assumptions:
0. The concept of "outreaches" in the existing dashboard corresponds to "outreach campaigns" that are undertaken by community businesses with their stakeholders for various reasons.
1. An outreach campaign is "owned" by an organisation not by a particular volunteer or CB admin.
2. An outreach campaign may involve one or more individual meetings between representatives of the community business and stakeholders.
3. A single meeting may take one of several forms (currently "first contact", "follow-up" and "event").
4. All meeting types are appropriate for all outreach campaigns
5. The concept of "outreach types" and "outreach child types" can be explained as: An "outreach type" is a category of activity about which the outreach is concerned (e.g. Asset Transfer). An "outreach child type" is the "target" of (or counter-party to) the outreach. Each "outreach type" has a set of valid "targets" for which that type of outreach makes sense. Some of these "targets" are valid for several "outreach types".

**Comment by SonjaTwine** [comment]
This is great. 
All of your assumptions are true.

For the last one:
Subscriptions types that I can envisage are
1. "Sector admin"/"Superadmin" access - purchases subscriptions on behalf of its members, and has a view of their (aggregated, anonymised) data, can renew and cancel subscriptions for its members.
2. PTC admin - the Twine team only, has access to the above but can edit and manage more features, and has complete view of all (personal and organisational) data of all organisations using Twine
3. "CB admin - full package" - has access to one organisation's Frontline account, with associated visitor app account

**Comment by SonjaTwine** [comment]
This is great.
All of your assumptions are true.

For the last one:
Subscriptions types that I can envisage are


1.	PTC admin - the Twine team only
a.	Can see aggregated data of all orgs through version of superadmin dashboard, but have additional management function (edit training dates etc)
b.	Can click through to view the same pages as a CB admin on the visitor app
c.	Can view individual logs for outreach and volunteering for all organisations – same functionality as current php web app
d.	Can create (through hubspot?) organisation profiles
e.	Can view every organisation’s Frontline account (already functional)
2.	"Sector admin"/"Superadmin"  - purchases subscriptions on behalf of its members
a.	Can view aggregated, anonymised data from all members
b.	Can cancel, assign, and renew subscriptions for members. These subscriptions could be “full package”, “visitor app”, “volunteer app”
3.	"CB admin - full package"
a.	Has one organisational access to Frontline
b.	Has same organisational access to Visitor app – CB admin
c.	Has their organisation set up on the volunteer app – unlimited number of volunteer and volunteer admin accounts
4.	“CB admin – visitor app”
a.	Has one organisational access to visitor app – CB admin, with unlimited visits and visitors
5.	“CB admin – volunteer app”
a.	Has their organisation set up on the volunteer app – unlimited number of volunteer and volunteer admin accounts

**Comment by eliascodes** [comment]
Update:

![screen shot 2018-06-04 at 14 09 19](https://user-images.githubusercontent.com/12719553/40919282-f75fcd88-6800-11e8-9329-2ef1b58f234f.png)

**Comment by eliascodes** [comment]
### Hierarchies
* Organisation
  * Funding Body
  * Community business

### Significant Relationships
```
Funding body         IS         Organisation
Funding body         HAS MANY   Funding programmes
Funding body         HAS MANY   Community businesses
Funding programme    HAS MANY   Subscriptions
Subscription         HAS ONE    Subscription type
Subscription         HAS ONE    Frontline account
Subscription         HAS ONE    Organisation AS owner
Subscription         HAS ONE    Organisation AS beneficiary
Training session     HAS ONE    Organisation
Community business   IS         Organisation
Community business   HAS ONE    Region
Community business   HAS ONE    Sector
Community business   HAS MANY   Feedback
Community business   HAS MANY   Outreach campaigns
Outreach campaign    HAS ONE    Outreach type
Outreach campaign    HAS MANY   Outreach meetings
Outreach type        HAS MANY   Outreach targets
Outreach meeting     HAS MANY   Meeting types
Outreach meeting     HAS ONE    User
User                 HAS MANY   Roles ACROSS MANY Organisations
Role                 HAS MANY   Permissions
Volunteer log        HAS ONE    User
Volunteer log        HAS ONE    Community business
Volunteer log        HAS ONE    Volunteer activity
Visit                HAS ONE    User
Visit                HAS ONE    Visit activity
Visit                HAS ONE    Community business
```

**Comment by SonjaTwine** [comment]
Thank you Elias!
This looks good, the only part of your list I'm wondering about is
Outreach campaign    HAS ONE    Outreach type
- since "campaign" is not within the current vocabulary of the app, but definitely the right concept, isn't it basically "Outreach campaign IS Outreach type"?

"Training session HAS ONE Organisation
    This assumes training sessions can be delivered to funding bodies as well as community businesses." - that is true, we will be doing both. 
Thought on future though: We haven't figured out exactly how we are going to log training sessions on the "superadmin dashboard", but it would be great if that included a way to signal 
Training session HAS MANY Organisations, at least for practically logging it?
Scenario to imagine here: we'd want to run group trainings because we need to get more efficient, so we would ask for example Funder X to bring together ten of its community business members around Sheffield so that Edward can run a training with all of them at the same time. It would be great if we could afterwards just tell the database "organisation a, b, c, d, e, f, g, h, i, j all received training today".

And yes to Subscription has one Frontline account, definitely, always.

**Comment by eliascodes** [comment]
> since "campaign" is not within the current vocabulary of the app, but definitely the right concept, isn't it basically "Outreach campaign IS Outreach type"?

I don't think so, unless I'm misunderstanding. "Outreach type" is just a set of values, namely: 
* Community Share Issue
* Crowdfunding (donations)
* Asset Transfer
* Community Energy Project
* Community Housing Project
* Public Services Commissioning

In our model, each campaign can be based on one of these only.

**Comment by SonjaTwine** [comment]
That's true. No worries then!

**Comment by astroash** [comment]
Questions that came up whilst I was designing the api today:

- Do we want `eventDate` and `createdAt` for training session?
- Do we want a `userId` in outreach campaign so we know who created it?

**Comment by eliascodes** [comment]
> Do we want eventDate and createdAt for training sessions & outreach meetings?

Probably

> Do we want a userId in outreach campaign so we know who created it?

Don't think so.

**Comment by SonjaTwine** [comment]
Another addition, sorry: was chatting to PTC programmes managers, and it would be useful if we could add the following:

1) For a user of the volunteer app (both volunteer and admin), there should be a 
varchar field on their profile to indicate 
- "volunteer", "part-time paid staff", "full-time paid staff". 
That should not be confused with "role", since it is not supposed to have any impact on the app they are seeing or the access they have to the different software parts, (i.e. it is unrelated to whether they are an admin on the mobile app, a volunteer, a visitor). It's just meant to be part of the "user" table if I understand that correctly, an attribute similar to "gender". What that would enable us to do, though, is track how many people are actually part-time or full-time employed at CBs, and also how often volunteers go on to become paid staff (that's a key part of some of PTC's impact objectives).
As mentioned yesterday, we can make the changes on the actual mobile app front end at some point after you're done with the database migration as it's not essential right now, but let's enable the functionality there?

2) Similarly, just putting the outreach bits here that we discussed yesterday: again, no need to make changes to the mobile app now, but if it's easier to have this enabled on the database already, let's add
for each Outreach meeting
- "Interaction partner name" (free text field, optional)
- "Interaction partner organisation" (free text field, optional)
- "Subject of meeting" (free text field, optional)
I do have some evidence that users would want that, we can confirm interface changes at some point in late 2018 when the programme it was designed for actually kicks off.

PS: is this the right place to put this? Shall we open a backlog on a project separate to the API move kanban, so we can save these feature changes there until they move up on the priority list?

**Comment by eliascodes** [comment]
> is this the right place to put this? Shall we open a backlog on a project separate to the API move kanban, so we can save these feature changes there until they move up on the priority list?

I've created a project for a [feature pipeline](https://github.com/orgs/TwinePlatform/projects/2), take a look at the description and feel free to stick up some issues in `hq` about some of the features we've mentioned in the last couple of weeks.

**Comment by SonjaTwine** [comment]
Thanks, feature pipeline looks brilliant!

>    "Interaction partner name" (free text field, optional) - Is this the name of an individual? Will such meetings only be conducted with a single person?
Good point! Actually we don't want any individual names on here, that's a whole new question about GDPR that I'd be keen to avoid! Let's forget about that, and stick to "organisation" and "subject".

**Comment by astroash** [comment]
@eliascodes, do we want createdAt, modifiedAt, deletedAt for community_business_region and community_business_sector? I've added endpoints in the api to be able to modify these.

**Comment by eliascodes** [comment]
> @eliascodes, do we want createdAt, modifiedAt, deletedAt for community_business_region and community_business_sector? I've added endpoints in the api to be able to modify these.

I don't think so, they'll be populated by us, rather than any users.

**Comment by eliascodes** [comment]
Closing this as #6 was merged. Changes going forward should have new issues.
