### ISSUE TITLE
Aggregated data for visitor app graphs

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#143]
The visitor app displays a number of graphs about visitor demographics.
<img width="500" alt="screen shot 2018-09-07 at 11 47 52 am" src="https://user-images.githubusercontent.com/14337958/45215066-1b6f8f00-b294-11e8-8321-6c42a01a71d6.png">

These calculate the total visits based on filters broken up into:
- age
- gender
- activity

Previously this data was collected via 5 separate sql queries that applied the pages filtering [🔗](https://github.com/TwinePlatform/twine-visitor/blob/ae180eaf09a1d3d4acbd4c31b0018ec4687246f9/server/database/queries/users_chart_all.js#L37-L41 ):
```
    dbConnection.query(getVisitsNumbersQuery, [cbId]),
    dbConnection.query(getGenderNumbersQuery, [cbId]),
    dbConnection.query(getActivitiesNumbersQuery, [cbId]),
    dbConnection.query(getVisitorsByAge, [cbId]),
    dbConnection.query(getActivitiesQuery, [cbId]),
``` 

Options recreating this functionality on the new server:
- recreate sql queries to count data similar to above 
- grab all visits for a cb and create aggregated data in js

Using `count` in sql is a slow operation as it needs to read every row in the table, therefore running a number of `count` queries for one data set is less than ideal. There are a number of ways to speed this up, however I do not think that the added complexity is worth the benefit at this time. See [count performance](https://www.citusdata.com/blog/2016/10/12/count-performance/) for more details.

For now, I propose data is collected and processed on the server. `/me/visit-logs` handler will grab all visit data related to a cb and restructure in the following format:
```
{
  meta: {
    total: allRows,
    limit: number,
    offset: number,
  },
  result: {
    paginatedVisits: [{ one: visit }],
    aggregates: {
      gender: { boy: total, girl: total, nonbinary: total },
      age: { young: total, medium: total, oldLikeMe: total },
      activity: { activityName: total },
    },
  },
};
```

NOTE: this route would be specifically designed for the clients purposes rather than the wonderfully generic api design we currently have. In this scenario I think that the trade off is worth it. Some data can be moved to `meta` if preferred.

**Comment by eliascodes** [comment]
What is `meta.total: allRows`? Is that just the total number of rows or all the actual row objects?

What is `limit` and `offset`? Is it the limit/offset that's been requested by the client? If so, what's the point of sending this back to the client?

Are you saying that the reason for proposing this shape of response is to avoid using `COUNT(*)` on several queries?

The article you link to gives a performance level of ~85ms for a table with 1 million rows. We're far from that, and are likely to be for some time. IMO the performance argument isn't that relevant yet, and when it is, it's still likely to be cheaper to simply upgrade the database instance than make any special optimisations. It's also not at all clear to me that doing the post-processing in application code would actually be an optimisation, particularly if we do ever start reaching that 1M rows.

In a RESTful API, URLs describe resources. When I ask for `/community-businesses/me/visit-logs`, I expect to get visit logs in the payload. I think the change proposed above is in danger of designing the API to server the visitor app, instead of designing the API to represent the data. That will cause problems as other applications and features begin to be integrated.

IMO an `aggregates` endpoint is still useful here. We want to design the endpoint to be immediately useful for the visitor app, but not so restricted as to be useless or awkward for another application. This probably means we want to be able to specify statistics/filters dynamically.

A suggestion:

`GET /.../visit-logs/aggregates?gender=true&age[]=0&age[]=25&activity=true`
```
{
  "age": { // requested age-ranges
    "0-25": 3,
    "25+": 7
  },
  "gender": { // All genders
    "male": 2,
    "female": 3,
    "prefer not to say": 10
  },
  "activity": { // All activities
    "Wear Pink": 2,
    "Free Running": 10
  }
}
```

`GET /.../visit-logs/aggregates?gender=male&age[]=0&age[]=25&age[]=60&activity=true`
```
{
  "age": { // requested age-ranges
    "0-25": 3,
    "25-60": 6,
    "60+": 1
  },
  "gender": { // requested gender
    "male": 2
  },
  "activity": { // All activities
    "Wear Pink": 2,
    "Free Running": 10
  }
}
```

`GET /.../visit-logs/aggregates?gender=true&age[]=0&age[]=25&activity=Wear%20&Pink`
```
{
  "age": { // requested age-ranges
    "0-25": 3,
    "25+": 7
  },
  "gender": { // All genders
    "male": 2,
    "female": 3,
    "prefer not to say": 10
  },
  "activity": { // requested activities
    "Wear Pink": 2
  }
}
```

The above suggestions assumes the only statistic of interest is the "total" in any given category/filter, and that all filters specified in query params are separate, rather than describing an intersection. This is probably fine for now, but we may want to allow for variations of this in future.
