### ISSUE TITLE
🗜 typings for CommunityBusiness.add

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#186]
`CommunityBusiness.add` takes a partial CommunityBusiness, however there are specific keys that are needed for a minimum type.

Calling `await CommunityBusinesses.add(trx, { name: 'Zeldas Dungeon' });` does not give a typing error, but throws a knex error due to missing values. 

```bash
Undefined binding(s) detected when compiling SELECT query: select "community_business_region_id" from "community_business_region" where "region_name" = ?

```

The types should be made stricter and/or the method checks for the minimum values needed.

**Comment by eliascodes** [comment]
I think types can't be made stricter without having separate type declarations for each collection, but there might be another way I'm not aware of.

Not sure what the point of checks inside the method would be, they'd just throw anyway. This is what the DB constraints give us for free.

**Comment by eliascodes** [comment]
Potentially, but the point I was making is that the generic declaration we have here:

https://github.com/TwinePlatform/twine-api/blob/e14547db7a1ca6a1c85dfa211905dcda8c0db511/src/models/types.ts#L277-L287

...will no longer work, since we'd need different fields in the `Pick` for each model. Potentially, we could just have a second argument, something like:

```ts
type Collection<T extends Model, U extends string> = {
  ...
  add: (k: Knex, a: (Pick<T, U> & Partial<T>)) => Promise<Partial<T>>
}

type CommunityBusinessCollection = Collection<CommunityBusiness, 'name' | 'region'>
```

But I don't know if that would work for every method.

**Comment by eliascodes** [comment]
Referenced in #164, so closing
