### ISSUE TITLE
Api Design

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#4]
First attempt of api design:

Covers functionality for visitor app & native app (PHP app to be added). A number of previous named routes have been dropped in favor of HTTP methods, and `sort`/`search`/`page`/`[filter]` queries.

# New Api
## /sector
/sector
/sector/:id

/sector/:id/feedback
/sector/:id/visits
/sector/:id/activities

## /regions
/regions
/regions/:id

## /organisations
/organisations
/organisations/:id || whoami

/organisations/:id/feedback
/organisations/:id/visits
/organisations/:id/activities
/organisations/:id/users

/organisations/:id/volunteer_logs
/organisations/:id/meetings
/organisations/:id/outreach

## /users (does this want to be broken down for frontline?)
/users
/users/register
/users/login
/users/:id || whoami
/users/:id/password_reset

/users/:id/qr_code
/users/:id/qr_code/email
/users/:id/activities/:id (visit?)

/users/:id/volunteer_logs
/users/:id/volunteer_logs/:id
/users/:id/volunteer_logs/sync (potentially covered by POST)
/users/:id/meetings
/users/:id/meetings/sync (potentially covered by POST)
/users/:id/meetings/:id

**Comment by eliascodes** [comment]
What does `sync` mean here?

**Comment by astroash** [comment]
> What does sync mean here?

This is an endpoint used by the native app to upload offline local storage data to the server.

> What HTTP methods are being used for these endpoints?

If this looks vaguely okay I can document which current routes these endpoints will replace with relevant http methods.

**Comment by eliascodes** [comment]
> /sector

Probably a typo, but `sector` should be `sectors`; REST resources should be plural.

> /users/:id/qr_code

Is this simply fetching the qr_code of the corresponding user? If so, we shouldn't be creating an entire endpoint just for this. The QR code should be returned with the rest of the user model in `/users/:id`. If we really only want the QR code, we can use a field filter like `/users/:id?fields=qr_code`.

> /users/:id/qr_code/email 

REST endpoints are supposed to represent _resources_, which makes it sometimes a little awkward to represent _actions_ (such as sending an email). The way I usually do it is to represent the collection of emails that have been sent as a resource, to which we are adding: `POST /users/:id/emails`. We have a fixed number email types that we want to send, and we'll know them all in advance. It's worth thinking about whether it makes more sense to structure this URL as above (given that we might also want to make something like `POST /organisations/:id/emails` available), or instead make `emails` a top-level resource: `POST /emails/template/:id` with a body of `{ to: id, model: {...} }`.

> /users/:id/activities/:id (visit?)
> /organisations/:id/activities

This needs to be more specific, since we are now dealing with visit activities and volunteer activities.

> whoami

`me` is better because it's a noun instead of a question. A REST URL is the name of a resource.

It's worth thinking about whether it's more ergonomic to introduce aliases for the types of different users: `/volunteers`, `/visitors`, etc. It would make the intent of every URL clearer. At the moment the fact that `/users/:id/qr_code` only makes sense for visitors is entirely implicit.

What do you think about having the API written up as a JSON file. For example:

```json
{
  "title": "twine-api",
  "version": "0.1",
  "routes": {
    "/sectors": {},
    "/regions": {},
    "/genders": {},
    "/organisations": {},
    "/users": {
      "description": "",
      "/": {
        "GET": {
          "description": "Retrieve all users accessible with the given scopes",
          "auth": {},
          "scope": {},
          "query": {},
          "response": {}
        },
        "POST": {}
      },
      "/register": {
        "POST": {
          "auth": null,
          "scope": null,
          "body": {},
          "response": {}
        }
      },
      "/login": {
        "POST": {
          "auth": null,
          "scope": null,
          "body": {},
          "response": {}
        }
      },
      "/me": {
        "GET": {
          "auth": "any",
          "scope": "",
          "query": {}
        }
      },
      "/:id": {},
      "/:id/password/reset": {}
    },
    "/volunteers": {
      "description": "Alias for /users/** where user role is VOLUNTEER"
    },
    "/visitors": {
      "description": "Alias for /users/** where user role is VISITOR"
    }
  }
}
```

We (probably) can generate route templates and basic docs from it.

**Comment by astroash** [comment]
> /users/:id/qr_code
This would be a POST request replacing the current `/api/qr/generator` route which creates creates the qr code for the user

> /users/:id/qr_code/email
Yeah, this was going to be for resending emails. A top level email resource sounds good. 

> > /users/:id/activities/:id (visit?)
> >/organisations/:id/activities
>
>This needs to be more specific...

Yeah, this will probably need to be broken down into `visit_activites` and `volunteer_activites`.

> ~~whoami~~ me
✅

> What do you think about having the API written up as a JSON file.

Yeah, sounds good. What's the definition of "auth" and "scope" here?

**Comment by eliascodes** [comment]
> What's the definition of "auth" and "scope" here?

`auth` can be whether the route is authenticated, `scope` should be a list of required permissions, in some appropriate format (e.g. `"read_organisations_own"` or something, I dunno).

**Comment by astroash** [comment]
> ...make emails a top-level resource: POST `/emails/template/:id`

@eliascodes are you suggesting here that the template id's in these endpoints will be coupled to email templates on postmark?

**Comment by eliascodes** [comment]
> are you suggesting here that the template id's in these endpoints will be coupled to email templates on postmark?

No, we should certainly design our system to minimise the coupling to postmark, or indeed any third party. All I was getting at was that we know we'll have a fixed set of e-mail types to send. Whether we address them via (self-generated) ID numbers or named labels (e.g. `/emails?template=password_reset`) or something else is a design decision that we can make.

**Comment by astroash** [comment]
* all endpoints to serve one use case. This will change the way that users access information about higher up resources

eg. Users accessing info about their organisation will change from:  
`/organisations/:id `  
to:  
`/users/me/organisation`
