### ISSUE TITLE
Two additional attributes/tags for users

### ISSUE THREAD

**Issue by SonjaTwine** [TwinePlatform/twine-api#48]
Hi,
I'm putting this here so you have the earliest warning possible - PTC is still figuring out the details.

We will need two additional attributes for **individual users** - this will be collected via the sign up page for the **visitor** app and the **volunteer** app.

Disability: Yes/No/Prefer not to say/NA (this will be an optional question)
Ethnicity: (Likely to be a longer list of varchar. I'm trying to get a shorter version of the 2001 Census categories.)

We can make the front end changes to the two sign up pages later. (i.e. adding two additional questions with dropdowns, plus info text related to GDPR)

The visitor app will then feature two additional graphs in "visits" that are pie charts showing the shares of each category for both of the above attributes.
(and Frontline, too, for volunteers)

However, we will not make front end changes for this on the individual user profile that CB admins can see on the visitor or volunteer app. That way, CB admins will only work with anonymised data.

Thoughts/concerns/questions?

**Comment by eliascodes** [comment]
Thanks for the heads up. Sounds OK. The only thing I would say is that we should be aware that the more data we wish to collect from visitors _at signup_, the more burdensome/off-putting that process becomes for them.

If the number of fields increases much more in future it may be worth thinking about how to make the signup process at least _feel_ simpler/quicker, even if it isn't.

**Comment by SonjaTwine** [comment]
Thanks!
Yup, agreed!  I'll add that to the bits I'm discussing with Jem in the first week of August.
Will update here when I have details on the contents of the ethnicity bit, and also time frames!

**Comment by SonjaTwine** [comment]
Nope, apologies - following up!
What are the dependencies of this?

**Comment by eliascodes** [comment]
Nothing really, we've just made some up for now.

**Comment by SonjaTwine** [comment]
Great.
May I suggest adding "muggle", "wizard", "elf", "hobbit" if you haven't already...
No sorry, I'll get you that list.

**Comment by astroash** [comment]
@edwardwptc do we have a list of ethnicities to be used on the twine platform?

**Comment by edwardwptc** [comment]
The default choice would be the 2011 census list because if anyone has a problem with it, we can say it's the census choices and not ours... That list might be a bit long tho, Sonja said about shortening it but unless you have a reason to I'd just use it as is for the above reason. Ignore where it says "please specify", if you think that's ok?  

White
English/Welsh/Scottish/Northern Irish/British
Irish
Gypsy or White Traveller
Any other white background (please specify)

Mixed/Multiple Ethnic Background
White and Black Caribbean
White and Black African
White and Asian
Any other Mixed/Multiple ethnic background (please specify)

Asian/Asian British
Indian
Pakistani
Bangladeshi
Chinese
Any other Asian background (please specify)

Black / African / Caribbean / Black British
African
Caribbean
Any other Black / African / Caribbean background (please specify)

Other Ethnic Group
Arab
Any other ethnic background (please specify)

**Comment by astroash** [comment]
@edwardwptc do you want to keep capitalisation exactly the same as above? There is some inconsistencies as with capitalisation of "ethnicity" as I believe the first line of each group is meant to be a title rather than a dropdown option.

Also the above wording switches between "ethnic background" and "ethnic group", is this okay?

**Comment by edwardwptc** [comment]
Ah, thanks. Removed what were titles (you were right) and also please specify. Also happens to remove the issue between group/background and capitalization. Forgive delay in reply. 


English/Welsh/Scottish/Northern Irish/British
Irish
Gypsy or White Traveller
Any other white background

White and Black Caribbean
White and Black African
White and Asian
Any other Mixed/Multiple ethnic background

Indian
Pakistani
Bangladeshi
Chinese
Any other Asian background


African
Caribbean
Any other Black / African / Caribbean background

Arab
Any other ethnic background
